### ISSUE TITLE
Correct the behaviour of Event Subclasses in the Go Library

### ISSUE THREAD

**Issue by yannbu** [zenaton/zenaton-go#4]
As known for some times, the when subclassing and Event class, the child Event is not handled properly by Zenaton changes has to be done, in coordination between the engine, agent and client libraries.

For more details please check:

zenaton/rfcs#19

**Comment by mKurrels** [comment]
This shouldn't be an issue for the go library as it is for the other libraries, as we don't use inheritance or subclassing. I'm closing it for now.
